### ISSUE TITLE
This is actually not a balanced tree！！！

### ISSUE THREAD

**Issue by zongleiZhang** [conversant/rtree#10]
The R-tree established in this project can't guarantee the balance of the tree. In fact, R-tree described by Guttman is a balanced tree in "R-TREES: A DYNAMIC INDEX STRUCTURE FOR SPATIAL SEARCHING".

**Comment by jac18281828** [comment]
Thanks for the question @zongleiZhang Which split leaf approach are you using in your code?

**Comment by jac18281828** [comment]
Thanks for the feedback.  I suggest you experiment with different SplitLeaf implementations.
