### ISSUE TITLE
bug in branch

### ISSUE THREAD

**Issue by absolutelies** [conversant/rtree#3]
hi.I test the code and run some data and find some bug.
In branch.java  function add  should return this not child[i].return child[i] will miss some leaf.
here is code:
if(size < mMin) {
            for(int i=0; i<size; i++) {
                if(child[i].getRect().contains(tRect)) {
                    child[i] = child[i].add(t);
                    mbr = mbr.getMbr(child[i].getRect());
                    return child[i];//here should return this
                }
            }

**Comment by jac18281828** [comment]
Thanks much for the contribution.    This will be fixed in 1.0.3 to be cut soon.        Please feel free to contribute your tests in a PR, I will be glad to merge them in.

**Comment by jac18281828** [comment]
Fixed in 1.0.3 Release
