### ISSUE TITLE
Rect3d.getNDim() should return 3

### ISSUE THREAD

**Issue by twinprime** [conversant/rtree#4]
https://github.com/conversant/rtree/blob/0d792e3ca0980844c5c8225e854336a4fa2e1dfb/src/main/java/com/conversantmedia/util/collection/geometry/Rect3d.java#L88

Should return 3 instead

**Comment by jac18281828** [comment]
Yep - typo - thanks again!

**Comment by jac18281828** [comment]
Thanks @richkraft @twinprime
