### ISSUE TITLE
Error in "Branch.intersects(HyperRect rect, Consumer<T> consumer)"

### ISSUE THREAD

**Issue by twinprime** [conversant/rtree#5]
https://github.com/conversant/rtree/blob/0d792e3ca0980844c5c8225e854336a4fa2e1dfb/src/main/java/com/conversantmedia/util/collection/spatial/Branch.java#L197

This line should be

`child[i].intersects(rect, consumer);`

**Comment by jac18281828** [comment]
Yeah!  Good find!

**Comment by jac18281828** [comment]
Thanks @richkraft @twinprime
