### ISSUE TITLE
The constructor function of "RTree" is protected

### ISSUE THREAD

**Issue by hucaser** [conversant/rtree#7]
Hi:

It is kind of you to open your source code on github. But I would like to know why you make the constructor function of "RTree" protected?

I would like to use your RTree on my own project, but I find I could not new a RTree, because the constructor is protected.

Would you like to solve this problem?

**Comment by jazzido** [comment]
Hi,

I have the same question. We're trying to use RTree to replace JSI in [`tabula-java`](https://github.com/tabulapdf/tabula-java) (tabulapdf/tabula-java#224). 

Unless I'm missing something, there's no way to use `RTree` from outside its package.

Thanks!

**Comment by evanwht1** [comment]
RTree implements the SpatialSearch interface (similar to SpatialIndex from JSI). You should be using that interface instead of the concrete RTree type. You then can use SpatialSearches, which has 4 static factory methods, to create instances of RTree's.
