### ISSUE TITLE
Add examples to the README

### ISSUE THREAD

**Issue by crisbodnar** [conversant/rtree#9]
Could you add some example use cases to the README? It took me a while to read the code and see how exactly to create an RTree (constructors are protected and it is not so obvious that SpatialSearches should be used) and how to use them.

**Comment by jac18281828** [comment]
Thanks for your question, please feel free to ask for more clarity.   Short answers as follows:

There is a factory called SpatialSearches.

There are several examples in the "wiki" and repo itself - tests.
